# print('hello')
# print(' should I do it')
print('It\'s what you want')
print('backslash escap :\\')
print('up\down')
print('up\\down')
print('up\'\\down')
print('\\-\\')
print('\-\ ')
print('Basri - 24July18 08:07')
